#ifndef ERROR_THRESHOLDS_H
#define ERROR_THRESHOLDS_H

#define FCVOLT_MAX 30.8
#define FCVOLT_MIN 12
#define CAPVOLT_MAX 32
#define CAPVOLT_MIN 12
#define PRESSURE_MIN 5
#define PRESSURE_MAX 8
#define MAX_FC_CURR 30
#define MAX_CAP_CURR 30


#endif
