#ifndef ERROR_THRESHOLDS_H
#define ERROR_THRESHOLDS_H

#define FCVOLT_MAX 50
#define FCVOLT_MIN 12
#define CAPVOLT_MAX 50
#define CAPVOLT_MIN 12
#define PRESSURE_MIN 4
#define PRESSURE_MAX 8
#define MAX_FC_CURR 30
#define MAX_CAP_CURR 30
#define TEMP_MAX 70


#endif
